# Site settings
author: Dimitri Gedda
title: Refreshing Waves In A Coding Ocean
header-img: img/home-bg.png
email: gratitudeadore@fastmail.com
copyright_name: Dimitri Gedda
description: > # this means to ignore newlines until "baseurl:"
  Well Hello There!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chimesindeed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
